export const TEXTURE_TYPE = {
  CUBE_TEXTURE: 'CUBE_TEXTURE',
  TEXTURE: 'TEXTURE',
  GLTF_MODEL: 'GLTF_MODEL',
};
export const TEXTURE_NAME = {
  ENVIRONMENT_MAP_COUBE_TEXTURE: 'ENVIRONMENT_MAP_COUBE_TEXTURE',
  FLOOR_COLOR_TEXTURE: 'FLOOR_COLOR_TEXTURE',
  FLOOR_NORMAL_TEXTURE: 'FLOOR_NORMAL_TEXTURE',
  FOX_MODEL: 'FOX_MODEL',
  PORTAL_MODEL: 'PORTAL_MODEL',
  PORTAL_TEXTURE: 'PORTAL_TEXTURE',
};

export const PORTAL_DEFAULTS = {
  POLE_LIGHT_A: 'poleLightA',
  POLE_LIGHT_B: 'poleLightB',
  PORTAL_LIGHT: 'portalLight',
  BAKED: 'baked',
};
